# Generated by Django 5.0.6 on 2024-06-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="stream", old_name="user", new_name="host",),
    ]
