# Generated by Django 5.0.6 on 2024-06-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_is_ended_stream_is_live_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
