# Generated by Django 5.0.6 on 2024-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="is_ended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stream",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
    ]
